source 'http://rubygems.org'

gem 'sinatra'

gem 'rack'
gem 'rack-contrib'
gem 'rack-test-accepts'

gem 'sprockets'
gem 'sass'

gem 'puma'

group :development, :test do
  gem 'simplecov'
  gem 'simplecov-html'
  gem 'rspec'
  gem 'rack-test'
  gem 'guard-rspec'
end