source 'http://rubygems.org'
gem 'grape'
gem 'grape-entity'
gem 'multi_json'
gem 'activemodel'

gem 'redis'
gem 'redis-namespace'
gem 'redis-persistence'

gem 'rack'
gem 'rack-contrib'
gem 'rack-test-accepts'
gem 'rack-cors'

gem 'puma'

group :development, :test do
  gem 'simplecov'
  gem 'simplecov-html'
  gem 'rspec'
  gem 'rspec_junit_formatter'
  gem 'rack-test'
  gem 'guard-rspec'
end
