apiVersion: v1
kind: Service
metadata:
  name: phonebook-frontend__SUFFIX__
  namespace: default
  labels:
    app: phonebook-frontend
    stage: __STAGE__
spec:
  selector:
    app: phonebook-frontend
  ports:
  - name: phonebook-frontend
    port: 80
    targetPort: 9292
    protocol: TCP
