apiVersion: v1
kind: Service
metadata:
  name: phonebook-backend__SUFFIX__
  namespace: default
  labels:
    app: phonebook-backend
    stage: __STAGE__
spec:
  selector:
    app: phonebook-backend
  ports:
  - name: phonebook-backend
    port: 80
    targetPort: 9293
    protocol: TCP
